In [ ]:
# 1) Creating Numpy Arrays

import numpy as np
print(np.version.version)

arr1=np.array([1,2,3,4,5])
print(arr1)

arr2=np.array([[1,2,3],[3,4,7]])
print(arr2)

print(arr1.ndim)
print(arr2.ndim)

print(arr1.dtype)
print(arr2.dtype)

print(arr1.size)
print(arr2.size)

print(arr1.itemsize)
print(arr2.itemsize)

print(arr2.shape)

print(arr2.reshape(3,2))



1.21.6
[1 2 3 4 5]
[[1 2 3]
 [3 4 7]]
1
2
int64
int64
5
6
8
8
(2, 3)
[[1 2]
 [3 3]
 [4 7]]


In [ ]:
#2) Slicing of Arrays
arr1=np.array([4,5,6,3,9,7])
print(arr1)
print(arr1[2:5])
print()

arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2[0:1,0:2])


[4 5 6 3 9 7]
[6 3 9]

[[1 2 3]
 [4 5 6]]
[[1 2]]


In [ ]:
#3)Join and Splitting of Numpy Arrays
arr1=np.array([4,5,6,7])
arr2=np.array([3,4,1])
arr3=np.concatenate([arr1,arr2])
print(arr3)
print()

arr1=np.array([[1,2,3],[3,4,5]])
arr2=np.array([[6,7,8],[9,11,10]])
arr3=np.concatenate([arr1,arr2],axis=0)
print(arr3)
print()

arr1=np.array([4,5,6,3,9])
print(arr1)
print(np.array_split(arr1,3))
print()

arr1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr1)
print(np.array_split(arr1,3))
print()


[4 5 6 7 3 4 1]

[[ 1  2  3]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 11 10]]

[4 5 6 3 9]
[array([4, 5]), array([6, 3]), array([9])]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]



In [ ]:
#4)Searching elements in an Array
arr1=np.array([1,2,3,4,5,4,4])
print(arr1)
result = np.where(arr1 == 4)
print("Elements with value 4 exists at following indices:", result[0])
print()

arr1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr1)
result = np.where(arr1 == 5)
print("Value 5 exists at following coordinate:", result)
print()

arr1=np.array([1,2,3,4,5,6,7,8])
print(arr1)
result1=np.where(arr1%2==0)
result2=np.where(arr1%2 !=0)
print("Indices of even elements:",result1[0])
print("Indices of odd elements:",result2[0])

[1 2 3 4 5 4 4]
Elements with value 4 exists at following indices: [3 5 6]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Value 5 exists at following coordinate: (array([1]), array([1]))

[1 2 3 4 5 6 7 8]
Indices of even elements: [1 3 5 7]
Indices of odd elements: [0 2 4 6]


In [ ]:
#5)Sorting of arrays
arr1=np.array([6,5,1,2,9,10,36,7])
print(arr1)
print(np.sort(arr1))
print(np.sort(arr1)[::-1])
print()

arr1=np.array([[5,3,7],[8,10,6],[40,-2,7]])
print(np.sort(arr1))
a_idx = np.argsort(-arr1)
sort_array = np.take_along_axis(arr1, a_idx, axis=1)
print(sort_array)

[ 6  5  1  2  9 10 36  7]
[ 1  2  5  6  7  9 10 36]
[36 10  9  7  6  5  2  1]

[[ 3  5  7]
 [ 6  8 10]
 [-2  7 40]]
[[ 7  5  3]
 [10  8  6]
 [40  7 -2]]


In [ ]:
#6)Random number generation
import numpy as np
from numpy import random
arr=random.randint(20, size=(6))
print(arr)
print()


arr = random.rand(5)
print(arr)
print()



arr = random.randint(50, size=(3, 5))
print(arr)
print()

arr = random.rand(3, 5)
print(arr)
print()

arr=np.array([6,5,1,2,9,10,36,7])
np.random.shuffle(arr)
print(arr)
print()

arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.random.shuffle(arr)
print(arr)
print()



[ 7 15  9  9 19  8]

[0.56433996 0.69507078 0.30989255 0.20740315 0.94757072]

[[ 1 37 22  1  9]
 [23 41 10 10 49]
 [11 35 14 21 45]]

[[1.21369449e-01 9.24629618e-01 3.23610950e-01 3.57790146e-01
  7.04055518e-01]
 [9.33844702e-01 6.39919295e-01 2.12781191e-01 6.78334326e-01
  6.77956528e-01]
 [7.00432234e-01 4.77578166e-01 6.09914922e-01 8.01830556e-05
  6.36612536e-01]]

[10  6  7 36  1  2  9  5]

[[ 4  5  6]
 [ 1  2  3]
 [ 7  8  9]
 [10 11 12]]



In [13]:
#PART B
import pandas as pd
import numpy as np
wine_data = pd.read_csv('winequality-red.csv')


arr=wine_data.to_numpy()
print(arr)
wine_data.describe()
print(arr.shape)

Y = arr[0:1144,-2:-1]
print(Y.shape)
print(Y)

X = arr[0:1144,0:12]
print(X.shape)



[['7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5']
 ['7.8;0.88;0;2.6;0.098;25;67;0.9968;3.2;0.68;9.8;5']
 ['7.8;0.76;0.04;2.3;0.092;15;54;0.997;3.26;0.65;9.8;5']
 ...
 ['6.3;0.51;0.13;2.3;0.076;29;40;0.99574;3.42;0.75;11;6']
 ['5.9;0.645;0.12;2;0.075;32;44;0.99547;3.57;0.71;10.2;5']
 ['6;0.31;0.47;3.6;0.067;18;42;0.99549;3.39;0.66;11;6']]
(1599, 1)
(1144, 0)
[]
(1144, 1)
